import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, signInAnonymously } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { collection, getFirestore, onSnapshot } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { firebaseConfig } from "../firebase-config.js";

const els = { connection: document.querySelector("#connection"), notice: document.querySelector("#notice"), products: document.querySelector("#product-grid"), cart: document.querySelector("#cart"), total: document.querySelector("#total"), generate: document.querySelector("#generate-button"), clear: document.querySelector("#clear-button"), qrPanel: document.querySelector("#qr-panel"), qr: document.querySelector("#qr-code"), qrText: document.querySelector("#qr-text"), modal: document.querySelector("#topping-modal"), modalTitle: document.querySelector("#modal-title"), modalBase: document.querySelector("#modal-base"), toppings: document.querySelector("#topping-grid"), modalTotal: document.querySelector("#modal-total"), skip: document.querySelector("#skip-topping"), add: document.querySelector("#add-with-topping") };
const db = getFirestore(initializeApp(firebaseConfig));
const auth = getAuth();
let products = [];
let cart = [];
let pendingProduct = null;
let selectedToppings = [];
const yen = new Intl.NumberFormat("ja-JP", { style: "currency", currency: "JPY", maximumFractionDigits: 0 });

function isTopping(product) { return String(product.category ?? "").includes("トッピング"); }
function availableProducts() { return products.filter((product) => product.active && !product.soldOut && Number(product.orderCode) > 0); }
function renderProducts() { els.products.replaceChildren(); availableProducts().filter((product) => !isTopping(product)).forEach((product) => { const button = document.createElement("button"); button.className = "product"; button.dataset.color = String(product.colorCode ?? 1); button.innerHTML = `<span class="product-name"></span><span class="price"></span>`; button.querySelector(".product-name").textContent = product.name; button.querySelector(".price").textContent = yen.format(product.priceYen); button.onclick = () => openToppingModal(product); els.products.append(button); }); }
function renderCart() { els.cart.replaceChildren(); cart.forEach((product, index) => { const row = document.createElement("div"); row.className = "cart-row"; const text = document.createElement("span"); text.textContent = `${product.name}　${yen.format(product.priceYen)}`; const remove = document.createElement("button"); remove.textContent = "削除"; remove.onclick = () => { cart.splice(index, 1); renderCart(); }; row.append(text, remove); els.cart.append(row); }); const total = cart.reduce((sum, product) => sum + Number(product.priceYen), 0); els.total.textContent = `合計 ${yen.format(total)}`; els.generate.disabled = cart.length === 0; els.qrPanel.hidden = true; }
function openToppingModal(product) { pendingProduct = product; selectedToppings = []; const toppings = availableProducts().filter(isTopping); if (!toppings.length) return addPending(false); els.modalTitle.textContent = "トッピングを追加しますか？"; els.modalBase.textContent = `${product.name}　${yen.format(product.priceYen)}`; els.toppings.replaceChildren(); toppings.forEach((topping) => { const button = document.createElement("button"); button.className = "topping"; button.textContent = `${topping.name}\n${yen.format(topping.priceYen)}`; button.onclick = () => { const index = selectedToppings.findIndex((item) => item.id === topping.id); if (index >= 0) selectedToppings.splice(index, 1); else selectedToppings.push(topping); button.classList.toggle("selected", index < 0); updateModalTotal(); }; els.toppings.append(button); }); updateModalTotal(); els.modal.hidden = false; }
function updateModalTotal() { const total = [pendingProduct, ...selectedToppings].filter(Boolean).reduce((sum, product) => sum + Number(product.priceYen), 0); els.modalTotal.textContent = `この商品小計 ${yen.format(total)}`; els.add.textContent = selectedToppings.length ? `トッピングを追加（${selectedToppings.length}点）` : "トッピングなしで追加"; }
function addPending(withToppings) { if (!pendingProduct) return; cart.push(pendingProduct); if (withToppings) cart.push(...selectedToppings); pendingProduct = null; selectedToppings = []; els.modal.hidden = true; renderCart(); }
function generateQr() { const text = `FPO1:${cart.map((product) => Number(product.orderCode)).join("+")}`; els.qr.replaceChildren(); new window.QRCode(els.qr, { text, width: 250, height: 250, correctLevel: window.QRCode.CorrectLevel.M }); els.qrText.textContent = text; els.qrPanel.hidden = false; }
els.skip.onclick = () => addPending(false); els.add.onclick = () => addPending(true); els.clear.onclick = () => { cart = []; renderCart(); }; els.generate.onclick = generateQr;
signInAnonymously(auth).then(() => onSnapshot(collection(db, "products"), (snapshot) => { products = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })).sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name, "ja")); els.connection.textContent = "商品を更新中"; els.notice.textContent = ""; renderProducts(); }, (error) => { els.connection.textContent = "商品取得エラー"; els.notice.textContent = `商品を読み込めませんでした：${error.message}`; })).catch((error) => { els.connection.textContent = "接続エラー"; els.notice.textContent = `注文画面を開始できませんでした：${error.message}`; });
